- hosts: redmine-servers

  roles:
    - system
    
    - role: pg
      when: redmiene_db == "postgres"

    - role: mysql
      when: redmiene_db == "mysql"
    
    - ruby
    - redmine
    - apache

  post_tasks:
    - name: 完了
      debug:
        msg='インストールが完了しました。 http://{{ ansible_default_ipv4.address }}/redmine/ にアクセスしてください。'
